version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: app
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - strapi_net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: always
    volumes:
      - ./strapi:/usr/src/app
    ports:
      - '1337:1337'
    networks:
      - strapi_net

networks:
  strapi_net:
    driver: bridge
